var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__484c6701._.js")
R.c("server/chunks/ssr/_7f7767ec._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_8acd4d67.js")
R.c("server/chunks/ssr/[root-of-the-server]__449e1bd8._.js")
R.c("server/chunks/ssr/node_modules_63dba3f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/_mark2_clones_TASK-13_src_app_581aa4d2._.js")
R.c("server/chunks/ssr/_mark2_clones_TASK-13_src_app_layout_tsx_28595c50._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/_mark2_clones_TASK-13__next-internal_server_app__not-found_page_actions_4335ba37.js")
R.m(61729)
module.exports=R.m(61729).exports
