id: TASK-185
title: Test Done Task 1770596890611-1
description: test
phase: done
phase_agents: {}
phase_overrides: {}
blockers: []
priority: P2
artifacts: []
ports: []
worktrees: {}
created_by: human
merge_strategy: squash
auto_advance: true
auto_approve: false
created_at: 2026-02-09T00:28:10.614Z
updated_at: 2026-02-09T00:28:17.773Z
phase_entered_at: 2026-02-09T00:28:10.614Z
loop_count: 0
archived: true
archived_at: 2026-02-09T00:28:17.773Z
