id: TASK-298
title: Test Task from Playwright 1770338673439
description: This is an e2e test task
phase: pending
phase_agents: {}
phase_overrides: {}
blockers: []
priority: P2
artifacts: []
ports: []
worktrees: {}
created_by: human
merge_strategy: squash
auto_advance: true
auto_approve: false
created_at: 2026-02-06T00:44:36.031Z
updated_at: 2026-02-06T00:44:36.031Z
phase_entered_at: 2026-02-06T00:44:36.031Z
loop_count: 0
archived: false
