id: TASK-299
title: Task with Badge 1770338713472
description: ""
phase: pending
phase_agents: {}
phase_overrides: {}
blockers: []
priority: P2
artifacts: []
ports: []
worktrees: {}
created_by: human
story_id: STORY-133
merge_strategy: squash
auto_advance: true
auto_approve: false
created_at: 2026-02-06T00:45:13.894Z
updated_at: 2026-02-06T02:15:53.946Z
phase_entered_at: 2026-02-06T00:45:13.894Z
loop_count: 0
archived: true
archived_at: 2026-02-06T02:15:53.946Z
