id: TASK-90
title: When a story has all tasks done, give the option to archive the story
description: ""
phase: code_review
phase_agents: {}
phase_overrides: {}
blockers: []
priority: P2
artifacts:
  - name: design
    phase: design
    path: design-design-1773950347119-2bzzn7.md
    mime_type: text/markdown
    created_at: 2026-03-19T19:59:07.120Z
    source: agent
  - name: coding-summary
    phase: coding
    path: coding-coding-summary-1774022224350-ssize8.md
    mime_type: text/markdown
    created_at: 2026-03-20T15:57:04.350Z
    source: agent
  - name: test-results
    phase: testing
    path: testing-test-results-1774031179686-d7tfhy.md
    mime_type: text/markdown
    created_at: 2026-03-20T18:26:19.686Z
    source: agent
  - name: test-coverage-summary
    phase: testing
    path: testing-test-coverage-summary-1774031214096-hbvafq.md
    mime_type: text/markdown
    created_at: 2026-03-20T18:26:54.096Z
    source: agent
  - name: review
    phase: code_review
    path: code_review-review-1774033228404-yjqlna.md
    mime_type: text/markdown
    created_at: 2026-03-20T19:00:28.405Z
    source: agent
ports: []
worktrees: {}
created_by: human
merge_strategy: squash
auto_advance: true
auto_approve: false
created_at: 2026-03-19T19:53:37.419Z
updated_at: 2026-03-20T19:00:28.405Z
phase_entered_at: 2026-03-20T18:57:26.937Z
loop_count: 0
archived: false
