id: TASK-87
title: Can we create a "archive all tasks" button in the Done step.
description: We have a lot of done tasks on a board, can we make it easier to move them to archived
phase: final_testing
phase_agents: {}
phase_overrides: {}
blockers: []
priority: P2
artifacts:
  - name: design
    phase: design
    path: design-design-1770590223237-04sp0o.md
    mime_type: text/markdown
    created_at: 2026-02-08T22:37:03.238Z
    source: agent
  - name: design
    phase: design
    path: design-design-1770590248376-oq825c.md
    mime_type: text/markdown
    created_at: 2026-02-08T22:37:28.377Z
    source: agent
  - name: design
    phase: design
    path: design-design-1770594464381-0uqyhn.md
    mime_type: text/markdown
    created_at: 2026-02-08T23:47:44.382Z
    source: agent
  - name: coding-summary
    phase: coding
    path: coding-coding-summary-1770594899690-qb348r.md
    mime_type: text/markdown
    created_at: 2026-02-08T23:54:59.691Z
    source: agent
  - name: test-results
    phase: testing
    path: testing-test-results-1770595125512-m3bs5m.md
    mime_type: text/markdown
    created_at: 2026-02-08T23:58:45.512Z
    source: agent
  - name: review
    phase: code_review
    path: code_review-review-1770595338230-vmj2e0.md
    mime_type: text/markdown
    created_at: 2026-02-09T00:02:18.230Z
    source: agent
ports: []
worktrees: {}
created_by: human
merge_strategy: squash
auto_advance: true
auto_approve: false
created_at: 2026-02-08T20:28:17.140Z
updated_at: 2026-02-09T00:05:14.096Z
phase_entered_at: 2026-02-09T00:05:14.096Z
loop_count: 0
archived: false
