id: TASK-92
title: Minimal Task
description: ""
phase: pending
phase_agents: {}
phase_overrides: {}
blockers: []
priority: P2
artifacts: []
ports: []
worktrees: {}
created_by: human
merge_strategy: squash
auto_advance: true
auto_approve: false
created_at: 2026-02-04T14:03:11.818Z
updated_at: 2026-02-06T02:02:32.305Z
phase_entered_at: 2026-02-04T14:03:11.818Z
loop_count: 0
archived: true
archived_at: 2026-02-06T02:02:32.305Z
