id: TASK-319
title: DnD Task B 1770338930408
description: ""
phase: testing
phase_agents: {}
phase_overrides: {}
blockers: []
priority: P2
artifacts: []
ports: []
worktrees: {}
created_by: human
story_id: STORY-144
merge_strategy: squash
auto_advance: true
auto_approve: false
created_at: 2026-02-06T00:48:52.188Z
updated_at: 2026-02-06T02:17:03.673Z
phase_entered_at: 2026-02-06T00:48:56.261Z
loop_count: 0
archived: true
archived_at: 2026-02-06T02:17:03.673Z
