id: TASK-74
title: No author task
description: Testing default created_by
phase: pending
phase_agents: {}
phase_overrides: {}
blockers: []
priority: P2
artifacts: []
ports: []
worktrees: {}
created_by: human
merge_strategy: squash
auto_advance: true
auto_approve: false
created_at: 2026-02-04T04:18:52.989Z
updated_at: 2026-02-04T04:18:52.989Z
phase_entered_at: 2026-02-04T04:18:52.989Z
loop_count: 0
archived: false
