id: TASK-41
title: When you click on a task with a large amount of description and title you can't read it all in the sidebar
description: The task and description are mega tiny in the sidebar (just above the phaase diagram)  We should place the description in a seperate tab of the sidebar all the way to the left.
phase: testing
phase_agents: {}
phase_overrides: {}
blockers: []
priority: P2
artifacts:
  - name: design
    phase: design
    path: design-design-1770176898943-f2g28o.md
    mime_type: text/markdown
    created_at: 2026-02-04T03:48:18.943Z
    source: agent
  - name: coding-summary
    phase: coding
    path: coding-coding-summary-1770177314958-vhxx4x.md
    mime_type: text/markdown
    created_at: 2026-02-04T03:55:14.958Z
    source: agent
ports: []
worktrees: {}
created_by: human
merge_strategy: squash
auto_advance: true
auto_approve: false
created_at: 2026-02-04T03:46:37.884Z
updated_at: 2026-02-04T03:58:28.381Z
phase_entered_at: 2026-02-04T03:58:28.381Z
loop_count: 0
archived: false
