id: TASK-98
title: startup-repro-32138
description: repro
phase: design
phase_agents: {}
phase_overrides: {}
blockers: []
priority: P2
artifacts: []
ports: []
worktrees: {}
created_by: human
merge_strategy: squash
auto_advance: true
auto_approve: false
created_at: 2026-02-08T23:29:52.048Z
updated_at: 2026-02-08T23:29:53.921Z
phase_entered_at: 2026-02-08T23:29:53.920Z
loop_count: 0
archived: false
