id: TASK-153
title: Test Done Task 1770596682350-3
description: test
phase: pending
phase_agents: {}
phase_overrides: {}
blockers: []
priority: P2
artifacts: []
ports: []
worktrees: {}
created_by: human
merge_strategy: squash
auto_advance: true
auto_approve: false
created_at: 2026-02-09T00:24:42.354Z
updated_at: 2026-02-09T00:24:42.354Z
phase_entered_at: 2026-02-09T00:24:42.354Z
loop_count: 0
archived: false
