id: TASK-41
title: When you click on a task with a large amount of description and title you can't read it all in the sidebar
description: The task and description are mega tiny in the sidebar (just above the phaase diagram)  We should place the description in a seperate tab of the sidebar all the way to the left.
phase: done
phase_agents: {}
phase_overrides: {}
blockers: []
priority: P2
artifacts:
  - name: design
    phase: design
    path: design-design-1770176898943-f2g28o.md
    mime_type: text/markdown
    created_at: 2026-02-04T03:48:18.943Z
    source: agent
  - name: coding-summary
    phase: coding
    path: coding-coding-summary-1770177314958-vhxx4x.md
    mime_type: text/markdown
    created_at: 2026-02-04T03:55:14.958Z
    source: agent
  - name: test-results
    phase: testing
    path: testing-test-results-1770177865069-v4svv2.md
    mime_type: text/markdown
    created_at: 2026-02-04T04:04:25.069Z
    source: agent
  - name: testing-summary
    phase: testing
    path: testing-testing-summary-1770177890020-00ptn2.md
    mime_type: text/markdown
    created_at: 2026-02-04T04:04:50.020Z
    source: agent
  - name: review
    phase: code_review
    path: code_review-review-1770178171677-8gqlrw.md
    mime_type: text/markdown
    created_at: 2026-02-04T04:09:31.678Z
    source: agent
  - name: final-test-results
    phase: final_testing
    path: final_testing-final-test-results-1770178795614-6kemqj.md
    mime_type: text/markdown
    created_at: 2026-02-04T04:19:55.614Z
    source: agent
  - name: test-plan
    phase: final_testing
    path: final_testing-test-plan-1770178862751-5ylx1n.md
    mime_type: text/markdown
    created_at: 2026-02-04T04:21:02.751Z
    source: agent
  - name: test-execution-report
    phase: run_test_plan
    path: run_test_plan-test-execution-report-1770179227450-14adn5.md
    mime_type: text/markdown
    created_at: 2026-02-04T04:27:07.450Z
    source: agent
ports: []
worktrees: {}
created_by: human
merge_strategy: squash
auto_advance: true
auto_approve: false
created_at: 2026-02-04T03:46:37.884Z
updated_at: 2026-02-09T00:13:11.854Z
phase_entered_at: 2026-02-04T04:28:30.062Z
loop_count: 0
archived: true
archived_at: 2026-02-09T00:13:11.834Z
