id: TASK-88
title: Fix the TMUX tab in the task details side panel
description: The Terminal tab has a very broken view of the Tmux shell running the CLI command.  It isn't live (you have to push refresh), doesn't support colors and doesn't support the TUIs well (they look very broken).  It's basically useless.  Can we make it be a true shell, that we can therotically even interact with?  Research typescript libraries that do this well, I'm sure they exist.
phase: testing
phase_agents: {}
phase_overrides: {}
blockers: []
priority: P2
artifacts:
  - name: design
    phase: design
    path: design-design-1773846819700-baqh63.md
    mime_type: text/markdown
    created_at: 2026-03-18T15:13:39.700Z
    source: agent
  - name: coding-summary
    phase: coding
    path: coding-coding-summary-1773848917348-ad5rn2.md
    mime_type: text/markdown
    created_at: 2026-03-18T15:48:37.349Z
    source: agent
ports: []
worktrees: {}
created_by: human
merge_strategy: squash
auto_advance: true
auto_approve: false
created_at: 2026-03-18T14:32:15.976Z
updated_at: 2026-03-18T15:50:53.856Z
phase_entered_at: 2026-03-18T15:50:53.856Z
loop_count: 0
archived: false
