// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/agents" | "/roles"
type AppRouteHandlerRoutes = "/api/agents" | "/api/bakeoffs" | "/api/bakeoffs/[id]" | "/api/branches" | "/api/config" | "/api/health" | "/api/ports" | "/api/reindex" | "/api/roles" | "/api/stories" | "/api/stories/[id]" | "/api/stories/[id]/tasks" | "/api/tasks" | "/api/tasks/[id]" | "/api/tasks/[id]/activity" | "/api/tasks/[id]/archive" | "/api/tasks/[id]/artifacts" | "/api/tasks/[id]/artifacts/open" | "/api/tasks/[id]/blockers" | "/api/tasks/[id]/git" | "/api/tasks/[id]/git/commit" | "/api/tasks/[id]/git/merge" | "/api/tasks/[id]/git/push" | "/api/tasks/[id]/git/sync" | "/api/tasks/[id]/open-ide" | "/api/tasks/[id]/phase" | "/api/tasks/[id]/phase/hook-complete" | "/api/tasks/[id]/phase/restart" | "/api/tasks/[id]/pr" | "/api/tasks/[id]/restore" | "/api/tasks/[id]/server" | "/api/tasks/[id]/server/terminal" | "/api/tasks/[id]/session" | "/api/tasks/[id]/storage" | "/api/tasks/[id]/terminal" | "/api/ws"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/agents": {}
  "/api/agents": {}
  "/api/bakeoffs": {}
  "/api/bakeoffs/[id]": { "id": string; }
  "/api/branches": {}
  "/api/config": {}
  "/api/health": {}
  "/api/ports": {}
  "/api/reindex": {}
  "/api/roles": {}
  "/api/stories": {}
  "/api/stories/[id]": { "id": string; }
  "/api/stories/[id]/tasks": { "id": string; }
  "/api/tasks": {}
  "/api/tasks/[id]": { "id": string; }
  "/api/tasks/[id]/activity": { "id": string; }
  "/api/tasks/[id]/archive": { "id": string; }
  "/api/tasks/[id]/artifacts": { "id": string; }
  "/api/tasks/[id]/artifacts/open": { "id": string; }
  "/api/tasks/[id]/blockers": { "id": string; }
  "/api/tasks/[id]/git": { "id": string; }
  "/api/tasks/[id]/git/commit": { "id": string; }
  "/api/tasks/[id]/git/merge": { "id": string; }
  "/api/tasks/[id]/git/push": { "id": string; }
  "/api/tasks/[id]/git/sync": { "id": string; }
  "/api/tasks/[id]/open-ide": { "id": string; }
  "/api/tasks/[id]/phase": { "id": string; }
  "/api/tasks/[id]/phase/hook-complete": { "id": string; }
  "/api/tasks/[id]/phase/restart": { "id": string; }
  "/api/tasks/[id]/pr": { "id": string; }
  "/api/tasks/[id]/restore": { "id": string; }
  "/api/tasks/[id]/server": { "id": string; }
  "/api/tasks/[id]/server/terminal": { "id": string; }
  "/api/tasks/[id]/session": { "id": string; }
  "/api/tasks/[id]/storage": { "id": string; }
  "/api/tasks/[id]/terminal": { "id": string; }
  "/api/ws": {}
  "/roles": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
