var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_global-error/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__b9356576._.js")
R.c("server/chunks/ssr/_8dab87b2._.js")
R.c("server/chunks/ssr/node_modules_next_dist_d8ccd4fc._.js")
R.c("server/chunks/ssr/[root-of-the-server]__449e1bd8._.js")
R.c("server/chunks/ssr/node_modules_63dba3f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/_mark2_clones_TASK-12_src_app_7e706ec8._.js")
R.c("server/chunks/ssr/b36f2_clones_TASK-12__next-internal_server_app__global-error_page_actions_5c221dd6.js")
R.m(61115)
module.exports=R.m(61115).exports
