import fs from 'fs';
import path from 'path';
import type { CLIAdapter } from './types';
import type { AgentInvocationParams } from '../../types';

/**
 * Adapter for OpenAI's Codex CLI.
 * Runs in full-auto mode with approval workflow.
 * Preparing for future MCP and session naming support.
 *
 * Note: buildCommand() performs filesystem I/O as a side effect
 * (writes MCP config and AGENTS.md). This matches the ClaudeCodeAdapter pattern.
 */
export class CodexCLIAdapter implements CLIAdapter {
  readonly toolId = 'codex-cli' as const;
  readonly supportsMCP = false;
  readonly supportsNaming = false;

  buildCommand(params: AgentInvocationParams): string {
    // Set up configuration files before building command
    this.setupMcpConfig(params);
    this.setupAgentsMd(params);

    // TODO: Verify exact Codex CLI flag names when integration is finalized.
    // --approval-mode full-auto is used instead of separate --full-auto and
    // --ask-for-approval flags to avoid potential flag conflicts.
    const parts: string[] = [
      'codex',
      '--approval-mode', 'full-auto',
      '--model', this.shellQuote(params.model),
      this.shellQuote(params.prompt),
    ];

    return parts.join(' ');
  }

  getEnvironment(params: AgentInvocationParams): Record<string, string> {
    return {
      NODE_ENV: 'development',
      MARK2_AGENT_TOKEN: params.agentToken,
      MARK2_API_URL: params.apiBaseUrl,
      MARK2_TASK_ID: params.taskId,
    };
  }

  /**
   * Set up MCP configuration for future MCP support.
   * Currently a placeholder - will be implemented when Codex adds MCP support.
   */
  private setupMcpConfig(params: AgentInvocationParams): void {
    const mcpConfigPath = path.join(params.workingDirectory, '.codex', 'mcp-config.json');
    // TODO: When Codex adds MCP support, restructure to match ClaudeCodeAdapter's
    // buildMcpConfig() format with command/args/env per server entry.
    const mcpConfig = {
      mcpServers: {},
      taskId: params.taskId,
      apiBaseUrl: params.apiBaseUrl,
    };

    // Ensure .codex directory exists (recursive is a no-op if it already exists)
    const codexDir = path.dirname(mcpConfigPath);
    fs.mkdirSync(codexDir, { recursive: true });

    // Write MCP config file
    fs.writeFileSync(mcpConfigPath, JSON.stringify(mcpConfig, null, 2), 'utf-8');
  }

  /**
   * Set up AGENTS.md file with agent definitions.
   * Creates a markdown file describing the agent's role and responsibilities.
   */
  private setupAgentsMd(params: AgentInvocationParams): void {
    const agentsMdPath = path.join(params.workingDirectory, 'AGENTS.md');

    const agentContent = `# Agent Configuration

## ${params.agentName}

**Phase:** ${params.phase}
**Model:** ${params.model}
**Task:** ${params.taskId}

### Role
${params.agentPrompt || 'AI coding agent'}

### Orchestration
${params.orchestrationPrompt ? '``````\n' + params.orchestrationPrompt + '\n``````' : 'Standard orchestration'}

### Task Description
${params.taskPrompt || params.prompt}

---
*Generated by Mark2 Orchestrator*
`;

    fs.writeFileSync(agentsMdPath, agentContent, 'utf-8');
  }

  private shellQuote(value: string): string {
    // Handle single quotes in the value by escaping them properly
    // Using the POSIX shell quoting format: 'text'\''more text'
    return `'${value.replace(/'/g, "'\\''")}'`;
  }
}
