// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agents">> = Specific
  const handler = {} as typeof import("../../src/app/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/roles">> = Specific
  const handler = {} as typeof import("../../src/app/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents">> = Specific
  const handler = {} as typeof import("../../src/app/api/agents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bakeoffs/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bakeoffs/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/bakeoffs/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bakeoffs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bakeoffs">> = Specific
  const handler = {} as typeof import("../../src/app/api/bakeoffs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/branches/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/branches">> = Specific
  const handler = {} as typeof import("../../src/app/api/branches/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/config">> = Specific
  const handler = {} as typeof import("../../src/app/api/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ports">> = Specific
  const handler = {} as typeof import("../../src/app/api/ports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reindex/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reindex">> = Specific
  const handler = {} as typeof import("../../src/app/api/reindex/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/roles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/roles">> = Specific
  const handler = {} as typeof import("../../src/app/api/roles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stories/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stories/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/stories/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stories/[id]/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stories/[id]/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/api/stories/[id]/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stories">> = Specific
  const handler = {} as typeof import("../../src/app/api/stories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[id]/activity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]/activity">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[id]/activity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[id]/archive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]/archive">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[id]/archive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[id]/artifacts/open/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]/artifacts/open">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[id]/artifacts/open/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[id]/artifacts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]/artifacts">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[id]/artifacts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[id]/blockers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]/blockers">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[id]/blockers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[id]/git/commit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]/git/commit">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[id]/git/commit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[id]/git/merge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]/git/merge">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[id]/git/merge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[id]/git/push/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]/git/push">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[id]/git/push/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[id]/git/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]/git">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[id]/git/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[id]/git/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]/git/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[id]/git/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[id]/open-ide/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]/open-ide">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[id]/open-ide/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[id]/phase/hook-complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]/phase/hook-complete">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[id]/phase/hook-complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[id]/phase/restart/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]/phase/restart">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[id]/phase/restart/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[id]/phase/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]/phase">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[id]/phase/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[id]/pr/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]/pr">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[id]/pr/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[id]/restore/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]/restore">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[id]/restore/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[id]/server/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]/server">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[id]/server/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[id]/server/terminal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]/server/terminal">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[id]/server/terminal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[id]/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]/session">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[id]/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[id]/storage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]/storage">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[id]/storage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[id]/terminal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]/terminal">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[id]/terminal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ws/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ws">> = Specific
  const handler = {} as typeof import("../../src/app/api/ws/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
