id: TASK-1
title: gfsdgfsd
description: ""
phase: pending
phase_agents: {}
phase_overrides: {}
blockers: []
priority: P2
artifacts: []
ports: []
worktrees: {}
created_by: human
merge_strategy: squash
auto_advance: true
auto_approve: false
created_at: 2026-01-31T21:55:22.292Z
updated_at: 2026-01-31T21:55:22.292Z
phase_entered_at: 2026-01-31T21:55:22.292Z
loop_count: 0
archived: false
