id: TASK-4
title: Test Archive YAML
description: Testing archive and YAML persistence
phase: pending
phase_agents: {}
phase_overrides: {}
blockers: []
priority: P2
artifacts: []
ports: []
worktrees: {}
created_by: test
merge_strategy: squash
auto_advance: true
auto_approve: false
created_at: 2026-01-31T22:01:31.866Z
updated_at: 2026-01-31T22:01:51.510Z
phase_entered_at: 2026-01-31T22:01:31.866Z
loop_count: 0
archived: false
