var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/stories/route.js")
R.c("server/chunks/node_modules_next_2c6c8648._.js")
R.c("server/chunks/node_modules_drizzle-orm_2d017f04._.js")
R.c("server/chunks/node_modules_yaml_dist_49c13b35._.js")
R.c("server/chunks/node_modules_zod_v4_da12b5b3._.js")
R.c("server/chunks/[externals]_better-sqlite3_c8aedf15._.js")
R.c("server/chunks/[root-of-the-server]__214afbda._.js")
R.c("server/chunks/b36f2_clones_TASK-12__next-internal_server_app_api_stories_route_actions_9e2edb3a.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/.mark2/clones/TASK-12/src/app/api/stories/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/.mark2/clones/TASK-12/src/app/api/stories/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
