var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_global-error/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__b9356576._.js")
R.c("server/chunks/ssr/_7f7767ec._.js")
R.c("server/chunks/ssr/node_modules_next_dist_9da8d137._.js")
R.c("server/chunks/ssr/[root-of-the-server]__449e1bd8._.js")
R.c("server/chunks/ssr/node_modules_63dba3f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/_mark2_clones_TASK-13_src_app_581aa4d2._.js")
R.c("server/chunks/ssr/b36f2_clones_TASK-13__next-internal_server_app__global-error_page_actions_1976b251.js")
R.m(88567)
module.exports=R.m(88567).exports
