var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/tasks/[id]/phase/restart/route.js")
R.c("server/chunks/[root-of-the-server]__29fa3376._.js")
R.c("server/chunks/_mark2_clones_TASK-13_src_lib_orchestration_engine_ts_5e68e48f._.js")
R.c("server/chunks/[root-of-the-server]__aca52f7d._.js")
R.c("server/chunks/[root-of-the-server]__6d65cddd._.js")
R.c("server/chunks/[root-of-the-server]__f408c708._.js")
R.c("server/chunks/[root-of-the-server]__fd05f270._.js")
R.c("server/chunks/_92141a13._.js")
R.c("server/chunks/e216b__next-internal_server_app_api_tasks_[id]_phase_restart_route_actions_1c570d8f.js")
R.m(77443)
module.exports=R.m(77443).exports
