var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/roles/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__e1930788._.js")
R.c("server/chunks/ssr/_8dab87b2._.js")
R.c("server/chunks/ssr/_089a4078._.js")
R.c("server/chunks/ssr/[root-of-the-server]__467d130b._.js")
R.c("server/chunks/ssr/node_modules_63dba3f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/_mark2_clones_TASK-12_src_app_7e706ec8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_mark2_clones_TASK-12_src_app_layout_tsx_7f8e0260._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_mark2_clones_TASK-12__next-internal_server_app_roles_page_actions_968b649b.js")
R.m(66635)
module.exports=R.m(66635).exports
