var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__a0be67ec._.js")
R.c("server/chunks/ssr/_7f7767ec._.js")
R.c("server/chunks/ssr/_c21b3967._.js")
R.c("server/chunks/ssr/[root-of-the-server]__467d130b._.js")
R.c("server/chunks/ssr/node_modules_63dba3f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/_mark2_clones_TASK-13_src_app_581aa4d2._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_mark2_clones_TASK-13_src_app_layout_tsx_28595c50._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_mark2_clones_TASK-13__next-internal_server_app_page_actions_27d11da1.js")
R.m(19324)
module.exports=R.m(19324).exports
